services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/varlib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  api:
    build: ./backend
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app_storage:/rails/storage
    depends_on:
      - db
    ports:
      - '3000:3000'
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - '8080:80'

volumes:
  postgres_data: {}
  app_storage: {}